keys:
  - &user_lucian age127p354uhmd7x24gdkvgtn9y9cczhc9xt7ngvetufyw6h58wmfp7q6aluex
  - &server_do_nixos_stage age19dq2g5ah84t5zp2kmte9jner4t502u6fwg60s37k2zj0ck0n4upqtmdfqt
  - &server_hetzner_main age17n0d7pl65p326rkpgw8sc7sap56ntjsc49racqw83jkjwdkyvsqsa02rrj
creation_rules:
  - path_regex: secrets/do-nixos-stage.yaml$
    key_groups:
      - age:
        - *user_lucian
        - *server_do_nixos_stage
  - path_regex: secrets/hetzner-main.yaml$
    key_groups:
      - age:
        - *user_lucian
        - *server_hetzner_main
